#!/bin/bash
#From raspi-config

do_audio() {
  AUDIO_OUT=$(whiptail --menu "Choose the audio output" 20 60 10 \
    "0" "Auto" \
    "1" "Force 3.5mm ('headphone') jack" \
    "2" "Force HDMI" \
    3>&1 1>&2 2>&3)
  if [ $? -eq 0 ]; then
    amixer cset numid=3 "$AUDIO_OUT"
  fi
}

description "Audio Configuration"
messagebox "HDMI/JACK"
do_audio
messagebox "Alsa Mixer"
alsamixer

